lang: en
logo:
  $link: logo-white.svg
repo: https://github.com/atomicojs/atomicojs.github.io/tree/master
socials:
  github: atomicojs/atomico
  twitter: uppercod
menu:
  - title:
      es: WebComponent con Atomico
      en: WebComponent with Atomic
    category: fundamentals
  - title:
      es: Api Hooks
      en: Api Hooks
    category: hooks
  - title:
      es: Guías
      en: Guides
    category: guides
aside:
  content:
    title: Contenido
