name: deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node install
        uses: actions/setup-node@v2.1.1
        with:
          node-version: "14.x"
      - run: npm install
      - run: npm run build
